from django.conf import settings

from defaults import ZONE_DEFAULTS_DEFAULT, DNS_MANAGER_RECIPES_DEFAULT

ZONE_DEFAULTS = getattr(settings, 'ZONE_DEFAULTS', ZONE_DEFAULTS_DEFAULT)

DNS_MANAGER_DOMAIN_MODEL = getattr(settings, 'DNS_MANAGER_DOMAIN_MODEL', None)
DNS_MANAGER_ZONE_ADMIN_FILTER = getattr(settings, 'DNS_MANAGER_ZONE_ADMIN_FILTER', None)
DNS_MANAGER_RECIPES = getattr(settings, 'DNS_MANAGER_RECIPES', DNS_MANAGER_RECIPES_DEFAULT)